version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influx-db
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB="locust-db"
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=my-organization
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - "./influxdb-data/:/var/lib/influxdb"
    command: /entrypoint.sh

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-data/:/var/lib/grafana"