version: '3'

services:
  master:
    build:
      context: locust-app/
      dockerfile: Dockerfile
    container_name: locust-master
    hostname: locust-master
    ports:
      - "8089:8089"
    command: -f /locust/locustfile/kafka_locust.py --master -H http://locust-master:8089

  worker:
    build:
      context: locust-app/
      dockerfile: Dockerfile
    command: -f /locust/locustfile/kafka_locust.py --worker --master-host locust-master

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./data-grafana/:/var/lib/grafana"

  influxdb:
    image: influxdb
    container_name: influx-db
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB="locust-db"
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=my-organization
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - "./influxdb-data/:/var/lib/influxdb"
    command: /entrypoint.sh

networks:
  backend: