version: '3'

services:
  master:
    build:
      context: .
    container_name: locust-master
    hostname: locust-master
    ports:
      - "8089:8089"
    command: -f /locust/locustfile/kafka_locust.py --master -H http://locust-master:8089

  worker:
    build:
      context: .
    container_name: locust-worker
    hostname: locust-worker
    command: -f /locust/locustfile/kafka_locust.py --worker --master-host locust-master