version: '3.5'

services:
  master:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app-master
    hostname: master
    networks:
      - locust
    volumes:
      - ./:/mnt/app
    ports:
      - "8089:8089"
    command: -f /mnt/app/locustfiles/locust_scenario.py --master --master-bind-port=5557

  worker:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: worker
    networks:
      - locust
    volumes:
      - ./:/mnt/app
    command: -f /mnt/app/locustfiles/locust_scenario.py --worker --master-host=master --master-port=5557

networks:
  locust:
    name: custom_network